//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int idCliente { get; set; }
        public int idTipoIdentidad { get; set; }
        public string nroIdentidad { get; set; }
        public int idEstado { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string solicitud { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
