//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public Habitacion()
        {
            this.ReservaDetalle = new HashSet<ReservaDetalle>();
        }
    
        public int idHabitacion { get; set; }
        public string nombre { get; set; }
        public int idEstado { get; set; }
        public decimal precio { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> plazasCama { get; set; }
        public Nullable<int> cantPlazasCama { get; set; }
        public Nullable<int> tieneEscritorio { get; set; }
        public Nullable<int> tieneRopero { get; set; }
        public Nullable<int> tieneFrigobar { get; set; }
        public Nullable<int> tieneTvSmart { get; set; }
        public Nullable<int> tieneDuchaLavamanos { get; set; }
        public Nullable<int> tieneTelefonoDirecto { get; set; }
        public string foto { get; set; }
    
        public virtual ICollection<ReservaDetalle> ReservaDetalle { get; set; }
    }
}
