//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System.Data.Objects;




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Mantenimiento.Datos.Entidades;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Mantenimiento.Datos.Base;

namespace Mantenimiento.Datos.Modelo
{

    ///<sumary>
    ///Contrato basico para trabajar con el contexto en el modulo principal
    ///</sumary>
    public interface IContexto :IUnidadTrabajo
    {
       
        #region Transaccion
    
        IObjectSet<TEntidad> CrearConjunto<TEntidad>() where TEntidad : class, IObjectWithChangeTracker;
       

        #endregion

                #region Propiedades del ObjectSet
    
        IObjectSet<Articulo> Articulo{get;}
        
    
        IObjectSet<ArticuloAutor> ArticuloAutor{get;}
        
    
        IObjectSet<ArticuloConclusion> ArticuloConclusion{get;}
        
    
        IObjectSet<ArticuloReferencia> ArticuloReferencia{get;}
        
    
        IObjectSet<Autor> Autor{get;}
        
    
        IObjectSet<DocumentoIdentidad> DocumentoIdentidad{get;}
        
    
        IObjectSet<Usuario> Usuario{get;}
        
    
        IObjectSet<ArticuloAdjunto> ArticuloAdjunto{get;}
        
    
        IObjectSet<Slider> Slider{get;}
        
    
        IObjectSet<Video> Video{get;}
        

                #endregion

    
    }
}
	
