//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDBCORAHEntities : DbContext
    {
        public EDBCORAHEntities()
            : base("name=EDBCORAHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public DbSet<Cliente> Cliente { get; set; }
        //public DbSet<Habitacion> Habitacion { get; set; }
        //public DbSet<Reserva> Reserva { get; set; }
        //public DbSet<ReservaDetalle> ReservaDetalle { get; set; }
    }
}
