//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaDetalle
    {
        public int idReservaDetalle { get; set; }
        public int idReserva { get; set; }
        public int idHabitacion { get; set; }
        public int idEstado { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> subTotal { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
