//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public Reserva()
        {
            this.ReservaDetalle = new HashSet<ReservaDetalle>();
        }
    
        public int idReserva { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fechaReserva { get; set; }
        public int idEstado { get; set; }
        public Nullable<decimal> importe { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ReservaDetalle> ReservaDetalle { get; set; }
    }
}
