//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios en este archivo pueden ocasionar un comportamiento incorrecto y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace Mantenimiento.Datos.Entidades
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Autor))]
    
    public partial class Usuario: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Propiedades primitivas
    
        [DataMember]
        public int idUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("La propiedad 'idUsuario' forma parte de la clave del objeto y no se puede modificar. Solo se pueden realizar cambios en las propiedades de clave cuando no se realiza un seguimiento del objeto o su estado es Agregado.");
                    }
                    _idUsuario = value;
                    OnPropertyChanged("idUsuario");
                }
            }
        }
        private int _idUsuario;
    
        [DataMember]
        public int idAlumno
        {
            get { return _idAlumno; }
            set
            {
                if (_idAlumno != value)
                {
                    ChangeTracker.RecordOriginalValue("idAlumno", _idAlumno);
                    if (!IsDeserializing)
                    {
                        if (Autor != null && Autor.idAutor != value)
                        {
                            Autor = null;
                        }
                    }
                    _idAlumno = value;
                    OnPropertyChanged("idAlumno");
                }
            }
        }
        private int _idAlumno;
    
        [DataMember]
        public string username
        {
            get { return _username; }
            set
            {
                if (_username != value)
                {
                    _username = value;
                    OnPropertyChanged("username");
                }
            }
        }
        private string _username;
    
        [DataMember]
        public string contrasenia
        {
            get { return _contrasenia; }
            set
            {
                if (_contrasenia != value)
                {
                    _contrasenia = value;
                    OnPropertyChanged("contrasenia");
                }
            }
        }
        private string _contrasenia;
    
        [DataMember]
        public int idEstado
        {
            get { return _idEstado; }
            set
            {
                if (_idEstado != value)
                {
                    _idEstado = value;
                    OnPropertyChanged("idEstado");
                }
            }
        }
        private int _idEstado;
    
        [DataMember]
        public Nullable<int> esAdmin
        {
            get { return _esAdmin; }
            set
            {
                if (_esAdmin != value)
                {
                    _esAdmin = value;
                    OnPropertyChanged("esAdmin");
                }
            }
        }
        private Nullable<int> _esAdmin;

        #endregion

        #region Propiedades de navegación
    
        [DataMember]
        public Autor Autor
        {
            get { return _autor; }
            set
            {
                if (!ReferenceEquals(_autor, value))
                {
                    var previousValue = _autor;
                    _autor = value;
                    FixupAutor(previousValue);
                    OnNavigationPropertyChanged("Autor");
                }
            }
        }
        private Autor _autor;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Autor = null;
        }

        #endregion

        #region Corrección de asociación
    
        private void FixupAutor(Autor previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Usuario.Contains(this))
            {
                previousValue.Usuario.Remove(this);
            }
    
            if (Autor != null)
            {
                if (!Autor.Usuario.Contains(this))
                {
                    Autor.Usuario.Add(this);
                }
    
                idAlumno = Autor.idAutor;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Autor")
                    && (ChangeTracker.OriginalValues["Autor"] == Autor))
                {
                    ChangeTracker.OriginalValues.Remove("Autor");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Autor", previousValue);
                }
                if (Autor != null && !Autor.ChangeTracker.ChangeTrackingEnabled)
                {
                    Autor.StartTracking();
                }
            }
        }

        #endregion

    }
}
