//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilitario.Resursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comun.Resursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR.
        /// </summary>
        internal static string Constante_Inicio {
            get {
                return ResourceManager.GetString("Constante_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARAR.
        /// </summary>
        internal static string Constante_Parar {
            get {
                return ResourceManager.GetString("Constante_Parar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal no puede ser null en AdministracionTiempoVidaPorEjecucionContexto.
        /// </summary>
        internal static string excepcion_AdministracionTiempoVidaPorEjecucionContexto_PrincipalNoPuedeSerNull {
            get {
                return ResourceManager.GetString("excepcion_AdministracionTiempoVidaPorEjecucionContexto_PrincipalNoPuedeSerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedor no encontrado en la configuración del IoC.
        /// </summary>
        internal static string excepcion_ContenedorNoEncontrado {
            get {
                return ResourceManager.GetString("excepcion_ContenedorNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje Inválido de Seguimiento .
        /// </summary>
        internal static string excepcion_MensajeInvalidoSeguimiento {
            get {
                return ResourceManager.GetString("excepcion_MensajeInvalidoSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a configuración predeterminada IocContainer que no se encuentra.
        /// </summary>
        internal static string excepcion_PredeterminadaConfiguracionIOC {
            get {
                return ResourceManager.GetString("excepcion_PredeterminadaConfiguracionIOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenedor predeterminado IoC no escontrado.
        /// </summary>
        internal static string excepcion_PredeterminadoConfiguracionIoC {
            get {
                return ResourceManager.GetString("excepcion_PredeterminadoConfiguracionIoC", resourceCulture);
            }
        }
    }
}
